# Generated by Django 5.1.6 on 2025-06-12 22:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_alter_user_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="home",
        ),
    ]
