# Generated by Django 5.2.3 on 2025-06-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_remove_user_home"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="custom_css",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Custom CSS"
            ),
        ),
    ]
