# Generated by Django 5.2.3 on 2025-06-12 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_alter_user_custom_css"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="home",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="home",
                to="main.page",
            ),
        ),
    ]
