# Generated by Django 5.2.3 on 2025-06-13 18:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0015_user_home"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="home",
        ),
    ]
