# Generated by Django 5.2.3 on 2025-06-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0016_remove_user_home"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="index_body",
            field=models.TextField(blank=True, null=True),
        ),
    ]
