# Generated by Django 5.2.3 on 2025-06-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0017_user_index_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="index_body",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
