# Generated by Django 5.2.3 on 2025-06-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0018_alter_user_index_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hide_nav",
            field=models.BooleanField(default=False),
        ),
    ]
