# Generated by Django 5.2.3 on 2025-06-13 20:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0019_user_hide_nav"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="hide_nav",
        ),
    ]
