# Generated by Django 5.2.3 on 2025-06-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0020_remove_user_hide_nav"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="show_nav",
            field=models.BooleanField(default=True),
        ),
    ]
