# Generated by Django 5.2.3 on 2025-06-13 22:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0021_user_show_nav"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="index_body",
            new_name="homepage",
        ),
    ]
