# Generated by Django 5.2.3 on 2025-06-13 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0022_rename_index_body_user_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="subscription_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="subscription_start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
