# Generated by Django 5.2.3 on 2025-06-14 03:23

from django.db import migrations, models

import main.validators


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0023_user_is_premium_user_stripe_customer_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="custom_domain",
            field=models.CharField(
                blank=True,
                help_text="To setup: Add an A record in your domain's DNS for 95.217.241.177",
                max_length=150,
                null=True,
                validators=[main.validators.validate_domain_name],
            ),
        ),
    ]
